### ISSUE TITLE
readqc not always specifying the correct output file

### ISSUE THREAD

**Issue by aclum** [microbiomedata/metaT_ReadsQC#7]
The issue is with this line
https://github.com/microbiomedata/metaT_ReadsQC/blob/f866a634a074823137c936e4d870bbff554f00f4/rqcfilter.wdl#L240

I this is not deterministic so sometimes you end up with the correct file and sometimes you end up with the rRNA file. 

For this run the file that should be input to assembly is 3.6 G
nmdcda@perlmutter:login02:/pscratch/sd/n/nmjaws/nmdc-prod/cromwell-executions/nmdc_metaT/31b007af-e328-40a7-926c-47ccb1f4789a/call-qc/metaTReadsQC/5fcf96a7-c485-4675-8df6-76573a8c8c06/call-qc/execution/filtered> ls -lh *fastq.gz
-rw-rw-r--+  2 nmjaws nmjaws 3.6G Aug  7 15:37 raw.anqrpht.fastq.gz
-rw-r--r--+ 11 nmjaws nmjaws 1.1G Aug  7 13:29 rRNA.fastq.gz

The finalize step the file size is the same for the rrna file and the clean file 
(nersc-python) nmdcda@perlmutter:login02:/pscratch/sd/n/nmjaws/nmdc-prod/cromwell-executions/nmdc_metaT/31b007af-e328-40a7-926c-47ccb1f4789a/call-qc/metaTReadsQC/5fcf96a7-c485-4675-8df6-76573a8c8c06/call-finish_rqc/execution> ls -lh *fastq.gz
-rw-r--r--+ 11 nmjaws nmjaws 1.1G Aug  7 13:29 Ga0491221_filtered.fastq.gz
-rw-r--r--+ 11 nmjaws nmjaws 1.1G Aug  7 13:29 Ga0491221_rRNA.fastq.gz

Please update the code to use a file suffix of 'anqrpht.fastq.gz' for the `filtered` output of task rqcfilter

**Comment by kaijli** [comment]
Created a branch, will merge when benchmark reruns confirmed good
